traefik_acme_email: "{{ vault_traefik_acme_email }}"

wireguard_address: "10.0.0.2/24"
wireguard_private_key: "{{ vault_wireguard_private_key }}"     
wireguard_peer_public_key: "Mtyw+MoEVPmJfAL1mxfESY1UJr6zdt5g1yb/20bdfWA=" 
wireguard_vps_public_ip: "{{ vault_wireguard_vps_public_ip }}"
wireguard_port: 51820
